# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: 'Default' 
  vmImage: 'windows-latest'
variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: NodeTool@0
  displayName: 'Use Node.js $(version)'
  inputs:
    versionSpec: 14.x

- task: Npm@1
  displayName: 'Install gulp'
  inputs:
    command: install
    workingDir: $(System.DefaultWorkingDirectory)
    packagesToInstall: gulp

- script: |
    echo "##vso[task.setvariable variable=PATH;]$(System.DefaultWorkingDirectory)/node_modules/.bin:$PATH"
  displayName: 'Set PATH environment variable'
    
- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'